nodeLinker: node-modules

npmScopes:
  engineering11:
    npmAuthToken: "${ENGINEERING11_NPM_AUTH_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com/engineering11/"
    npmRegistryServer: "https://npm.pkg.github.com/engineering11/"
  e11sandbox:
    npmAuthToken: "${ENGINEERING11_NPM_AUTH_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com/e11sandbox/"
    npmRegistryServer: "https://npm.pkg.github.com/e11sandbox/"


yarnPath: .yarn/releases/yarn-4.9.1.cjs
